import Foundation
import Logging

/// Maps a `WorkspaceProfile` to Warp's native launch-configuration YAML format.
///
/// Warp's launch configurations live under `~/.warp/launch_configurations/`
/// (note: plural `launch_configurations`, not `launch_configs` — the
/// in-code reference at `app/src/launch_configs/launch_config.rs` is the
/// **module** name, not the directory name; the test fixture at
/// `crates/integration/tests/data/test_launch_config.yaml` and the in-file
/// header comment confirm the on-disk path).
///
/// Schema reimplemented from the upstream `LaunchConfig` / `TabTemplate` /
/// `PaneTemplateType` / `CommandTemplate` structs (AGPL — referenced for
/// shape only, not vendored). Our minimum-viable mapping is one window /
/// one tab / one pane with the profile's directory as `cwd` and the profile's
/// `defaultCommands` as a list of `exec` entries on that pane.
///
/// Limitations vs the full Warp schema:
///   - We do not emit `env`. Warp's launch config schema does not expose a
///     top-level env map; environment variables are achieved per-command
///     via shell-prefixed `exec` strings. For v6.0 we keep them in the
///     private profile JSON only and let the user decide whether to inline
///     them into commands.
///   - We do not emit splits — single pane only.
///   - We do not emit `active_window_index` / `title` / `color`.
enum WarpLaunchConfig {

    /// Directory where Warp's launch configurations live.
    static var directory: URL {
        FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".warp")
            .appendingPathComponent("launch_configurations")
    }

    /// Sanitize a profile name into a safe filename. Warp lists configs by
    /// their on-disk filename; we keep it close to the profile name but
    /// strip filesystem-hostile characters.
    static func filename(forProfile name: String) -> String {
        let allowed = CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "-_."))
        let sanitized = String(name.unicodeScalars.map { allowed.contains($0) ? Character($0) : "-" })
        return "\(sanitized).yaml"
    }

    static func fileURL(forProfile name: String) -> URL {
        directory.appendingPathComponent(filename(forProfile: name))
    }

    /// Write a launch-config YAML for the given profile. Returns the file
    /// URL. Creates the parent directory if needed. Always overwrites; the
    /// header comment marks the file as generated.
    @discardableResult
    static func write(profile: WorkspaceProfile, logger: Logger) throws -> URL {
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let url = fileURL(forProfile: profile.name)
        let yaml = render(profile: profile)
        try yaml.write(to: url, atomically: true, encoding: .utf8)
        logger.info("wrote Warp launch config for '\(profile.name)' -> \(url.path)")
        return url
    }

    /// Remove the launch-config YAML if present. No-op if absent. Returns
    /// `true` if a file was actually deleted.
    @discardableResult
    static func remove(profileName: String, logger: Logger) -> Bool {
        let url = fileURL(forProfile: profileName)
        guard FileManager.default.fileExists(atPath: url.path) else { return false }
        do {
            try FileManager.default.removeItem(at: url)
            logger.info("removed Warp launch config: \(url.path)")
            return true
        } catch {
            logger.warning("failed to remove Warp launch config at \(url.path): \(error)")
            return false
        }
    }

    // MARK: - Rendering

    /// Render a minimal Warp launch-config YAML for the profile. The format
    /// is hand-rolled rather than via a YAML library — our shape is simple
    /// (no anchors, no flow style, no multi-doc) and a small dedicated
    /// emitter keeps the dependency footprint flat.
    static func render(profile: WorkspaceProfile) -> String {
        var lines: [String] = []
        lines.append("# Generated by claude-command-runner v6.0 — do not hand-edit unless you")
        lines.append("# also unlink it from the corresponding workspace profile, or your edits")
        lines.append("# will be overwritten on the next save_workspace_profile call.")
        lines.append("---")
        lines.append("name: \(yamlScalar(profile.name))")
        lines.append("windows:")
        lines.append("  - tabs:")
        lines.append("      - layout:")
        lines.append("          cwd: \(yamlScalar(expandTilde(profile.directory)))")
        if !profile.defaultCommands.isEmpty {
            lines.append("          commands:")
            for cmd in profile.defaultCommands {
                lines.append("            - exec: \(yamlScalar(cmd))")
            }
        }
        return lines.joined(separator: "\n") + "\n"
    }

    // MARK: - YAML scalar quoting

    /// Quote a YAML scalar conservatively: if the string is "plain-safe" we
    /// emit it bare; otherwise we double-quote and escape `\` and `"`.
    /// Plain-safe means: no leading whitespace, no leading special character,
    /// no embedded `: `, no `# ` (which would start a comment), no control
    /// characters, no surrounding whitespace, and not one of the reserved
    /// YAML keywords (true/false/null/yes/no/on/off and their casings,
    /// or anything that parses as a number).
    private static func yamlScalar(_ s: String) -> String {
        if needsQuoting(s) {
            let escaped = s
                .replacingOccurrences(of: "\\", with: "\\\\")
                .replacingOccurrences(of: "\"", with: "\\\"")
                .replacingOccurrences(of: "\n", with: "\\n")
                .replacingOccurrences(of: "\t", with: "\\t")
            return "\"\(escaped)\""
        }
        return s
    }

    private static func needsQuoting(_ s: String) -> Bool {
        if s.isEmpty { return true }
        if s.first?.isWhitespace == true || s.last?.isWhitespace == true { return true }
        if s.contains(": ") || s.contains(" #") || s.contains("\n") || s.contains("\t") { return true }
        let firstChars: Set<Character> = ["!", "&", "*", "?", "|", ">", "'", "\"", "%", "@", "`", "[", "]", "{", "}", ",", "#"]
        if let first = s.first, firstChars.contains(first) { return true }
        let reserved: Set<String> = [
            "true", "false", "null", "yes", "no", "on", "off",
            "True", "False", "Null", "Yes", "No", "On", "Off",
            "TRUE", "FALSE", "NULL", "YES", "NO", "ON", "OFF",
            "~", ""
        ]
        if reserved.contains(s) { return true }
        // Numeric-looking — quote to keep it a string.
        if Double(s) != nil { return true }
        return false
    }

    private static func expandTilde(_ path: String) -> String {
        return (path as NSString).expandingTildeInPath
    }
}
